name: .NET Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: FastInverseSquareRoot.sln                  # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: FastInverseSquareRoot.UnitTests/FastInverseSquareRoot.UnitTests.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Build solution
      run: dotnet build -c Release
      
    - name: Execute unit tests
      run: dotnet test -c Release

    - name: Run benchmarks
      run: dotnet run -c Release --project FastInverseSquareRoot.Benchmark/FastInverseSquareRoot.Benchmarks.csproj
